### ISSUE TITLE
[EXPIRED] Not working with Keepass 2.34

### ISSUE THREAD

**Issue by sergeevabc** [luelista/KeePassMPAGen#1]
![KeePassMPAGen is broken](https://i1.someimage.com/0MqRAz2.png)

Dear Max, could you investigate further and fix it if necessary?

**Comment by luelista** [comment]
Which steps are leading to this error message?

**Comment by sergeevabc** [comment]
1. Unpack Keepass 2.34.
2. Install KeePassMPAGen to Keepass folder.
3. Launch Keepass and select Generate password.
4. Choose “Use custom algorithm” and select MasterPasswordApp.
5. Change tab to Preview.

**Comment by sergeevabc** [comment]
1. Unpack Keepass 2.34.
2. Install KeePassMPAGen to Keepass folder.
3. Launch Keepass and select Generate password.
4. Choose “Use custom algorithm” and select MasterPasswordApp.
5. Change tab to Preview.

**Comment by sergeevabc** [comment]
Err… Hello?
